const charset = document.createElement('meta')
const viewport = document.createElement('meta')
const title = document.createElement('title')
const link =  document.createElement('link')
const font1 = document.createElement('link')
const font2 = document.createElement('link')
const font3 = document.createElement('link')
const font4 = document.createElement('link')

charset.setAttribute('charset', 'UTF-8')
viewport.setAttribute('name', 'viewport')
viewport.setAttribute('content', 'width=device-width, initial-scale=1.0')
link.setAttribute('rel', 'stylesheet')
link.setAttribute('href', 'css/style.css')
font1.setAttribute('rel', 'preconnect')
font1.setAttribute('href', 'https://fonts.googleapis.com')
font2.setAttribute('rel', 'preconnect')
font2.setAttribute('href', 'https://fonts.gstatic.com')
font2.setAttribute('crossorigin', '')
font3.setAttribute('rel', 'stylesheet')
font3.setAttribute('href', 'https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap')
font4.setAttribute('rel', 'stylesheet')
font4.setAttribute('href', 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap')


document.head.appendChild(charset)
document.head.appendChild(viewport)
document.head.appendChild(link)
document.head.appendChild(title)
document.head.appendChild(font1)
document.head.appendChild(font2)
document.head.appendChild(font3)
document.head.appendChild(font4)

export {title}